GCC = avr-gcc

MCU = atmega1280

CFLAGS = -mmcu=$(MCU) -Wall -Wextra -pedantic -Wstrict-prototypes -Os \
	-std=gnu99 -frename-registers -fshort-enums -fpack-struct -c
LDFLAGS = -mmcu=$(MCU) -Wl,-u,vfprintf -lprintf_min 


%.o: %.c
	$(GCC) $(CFLAGS) $< -o $@	

clean:
	rm -f $(OBJS) $(CLEAN)
